// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/search-properties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.57.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supa() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_properties_default = defineTool({
  name: "search_properties",
  title: "Search properties",
  description: "Search Supreme Empreendimentos' public real-estate catalog in Goi\xE2nia. Filter by purpose (venda/aluguel), property type, bedrooms, price range, or location text.",
  inputSchema: {
    purpose: z.enum(["venda", "aluguel"]).optional().describe("Buy (venda) or rent (aluguel)."),
    property_type: z.string().optional().describe("e.g. casa, apartamento, terreno, rural."),
    min_bedrooms: z.number().int().optional(),
    min_price: z.number().optional(),
    max_price: z.number().optional(),
    location_contains: z.string().optional().describe("Substring match on location/neighborhood."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input) => {
    const limit = input.limit ?? 10;
    let q = supa().from("public_properties").select("*").limit(limit);
    if (input.purpose) q = q.eq("purpose", input.purpose);
    if (input.property_type) q = q.eq("property_type", input.property_type);
    if (typeof input.min_bedrooms === "number") q = q.gte("bedrooms", input.min_bedrooms);
    if (typeof input.min_price === "number") q = q.gte("price", input.min_price);
    if (typeof input.max_price === "number") q = q.lte("price", input.max_price);
    if (input.location_contains) q = q.ilike("location", `%${input.location_contains}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-property.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.57.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supa2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_property_default = defineTool2({
  name: "get_property",
  title: "Get property details",
  description: "Fetch full public details for a single property by its ID.",
  inputSchema: {
    id: z2.string().describe("Property UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ id }) => {
    const { data, error } = await supa2().from("public_properties").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Property not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { property: data }
    };
  }
});

// src/lib/mcp/tools/featured-properties.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.57.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supa3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var featured_properties_default = defineTool3({
  name: "list_featured_properties",
  title: "List featured properties",
  description: "Return highlighted (featured) properties from Supreme Empreendimentos.",
  inputSchema: {
    limit: z3.number().int().min(1).max(20).optional().describe("Max results (default 6).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const { data, error } = await supa3().from("public_properties").select("*").eq("featured", true).limit(limit ?? 6);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, results: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "supreme-empreendimentos-mcp",
  title: "Supreme Empreendimentos MCP",
  version: "0.1.0",
  instructions: "Tools for the Supreme Empreendimentos real-estate catalog in Goi\xE2nia. Use `search_properties` to filter listings by purpose, type, bedrooms, price, or location; `list_featured_properties` for highlighted homes; `get_property` for full details by ID.",
  tools: [search_properties_default, featured_properties_default, get_property_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
