// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypkmorgcpooygsvhcpvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwa21vcmdjcG9veWdzdmhjcHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODY1MjAsImV4cCI6MjA3MjU2MjUyMH0.A8MoJFe_ACtVDl7l0crAyU7ZxxOhdWJ8NShaqSHBxQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detect if running in production (not in Lovable editor/preview)
const isProductionDomain = (() => {
  if (typeof window === 'undefined') return false;
  const hostname = window.location.hostname;
  // Production domains: lovable.app, custom domains, Vercel, etc.
  // NOT production: lovableproject.com (preview), localhost
  return !hostname.includes('lovableproject.com') && 
         !hostname.includes('localhost') && 
         !hostname.includes('127.0.0.1');
})();

// Use a safe storage to avoid crashes on Safari Private Mode and restricted environments
const safeStorage = (() => {
  try {
    if (typeof window === 'undefined') return undefined;
    const testKey = '__sb_test__';
    window.localStorage.setItem(testKey, '1');
    window.localStorage.removeItem(testKey);
    return window.localStorage;
  } catch {
    return undefined;
  }
})();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: Boolean(safeStorage),
    autoRefreshToken: true,
    // Use PKCE flow explicitly to bypass any external auth-bridge injection
    flowType: 'pkce',
    // In production, don't detect session from URL (prevents auth-bridge interference)
    detectSessionInUrl: !isProductionDomain,
  }
});